// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTaskInput struct {
	Title     string `json:"title"`
	ProjectID string `json:"projectID"`
}

type Mutation struct {
}

type Query struct {
}

type Task struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Status    string `json:"status"`
	ProjectID string `json:"projectID"`
}
