package graph

// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	

	"go-graphql-taskflow/internal/graph/generated"
	"go-graphql-taskflow/internal/graph/model"
)

// --------------------
// Mutation Resolver
// --------------------

func (r *mutationResolver) CreateTask(
	ctx context.Context,
	input model.CreateTaskInput,
) (*model.Task, error) {

	task := r.TaskService.CreateTask(
		input.Title,
		input.ProjectID,
	)

	return task, nil
}

// --------------------
// Query Resolver
// --------------------

func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	return []*model.Task{}, nil
}

// --------------------
// Resolver Wiring
// --------------------

func (r *Resolver) Mutation() generated.MutationResolver {
	return &mutationResolver{r}
}

func (r *Resolver) Query() generated.QueryResolver {
	return &queryResolver{r}
}

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }