package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"go-graphql-taskflow/internal/graph/generated"
	"go-graphql-taskflow/internal/graph/model"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	task, err := r.TaskService.CreateTask(
		input.Title,
		input.ProjectID,
	)

	if err != nil {
		return nil, err
	}

	return task, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	return []*model.Task{}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	type taskResolver struct{ *Resolver }
func (r *Resolver) Task() generated.TaskResolver {
	return &taskResolver{r}
}
func (r *taskResolver) Comments(ctx context.Context, obj *model.Task) ([]*model.Comment, error) {
	commentsMap, err := r.CommentService.GetCommentsByTaskIDs(ctx, []string{obj.ID})
	if err != nil {
		return nil, err
	}
	return commentsMap[obj.ID], nil
}
*/
